# Generated by Django 2.2.8 on 2020-05-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
